### ISSUE TITLE
Several antivirus detects floorp.exe as malware

### ISSUE THREAD

**Issue by jfdtse** [Floorp-Projects/Floorp-Portable#29]
I upload floorp.exe to Virustotal and 5 engines report as malware.

```
- _id: "YjA4Y2FkMDY4YTdiMWMxMmFhNWY1OWFlN2U2NDFkNzk6MTcyNTM5OTQ4OA=="
  _type: "analysis"
  date: 1725399488  # 2024-09-03 23:38:08 +0200 CEST
  results:
    APEX:
      category: "malicious"
      engine_name: "APEX"
      engine_update: "20240901"
      engine_version: "6.571"
      method: "blacklist"
      result: "Malicious"
    AVG:
      category: "undetected"
      engine_name: "AVG"
      engine_update: "20240903"
      engine_version: "23.9.8494.0"
      method: "blacklist"
      result: null
    Acronis:
      category: "undetected"
      engine_name: "Acronis"
      engine_update: "20240328"
      engine_version: "1.2.0.121"
      method: "blacklist"
      result: null
    AhnLab-V3:
      category: "undetected"
      engine_name: "AhnLab-V3"
      engine_update: "20240903"
      engine_version: "3.26.1.10507"
      method: "blacklist"
      result: null
    Alibaba:
      category: "undetected"
      engine_name: "Alibaba"
      engine_update: "20190527"
      engine_version: "0.3.0.5"
      method: "blacklist"
      result: null
    Antiy-AVL:
      category: "undetected"
      engine_name: "Antiy-AVL"
      engine_update: "20240903"
      engine_version: "3.0"
      method: "blacklist"
      result: null
    Arcabit:
      category: "undetected"
      engine_name: "Arcabit"
      engine_update: "20240903"
      engine_version: "2022.0.0.18"
      method: "blacklist"
      result: null
    Avast:
      category: "undetected"
      engine_name: "Avast"
      engine_update: "20240903"
      engine_version: "23.9.8494.0"
      method: "blacklist"
      result: null
    Avast-Mobile:
      category: "type-unsupported"
      engine_name: "Avast-Mobile"
      engine_update: "20240903"
      engine_version: "240903-02"
      method: "blacklist"
      result: null
    Avira:
      category: "undetected"
      engine_name: "Avira"
      engine_update: "20240903"
      engine_version: "8.3.3.20"
      method: "blacklist"
      result: null
    Baidu:
      category: "undetected"
      engine_name: "Baidu"
      engine_update: "20190318"
      engine_version: "1.0.0.2"
      method: "blacklist"
      result: null
    BitDefender:
      category: "undetected"
      engine_name: "BitDefender"
      engine_update: "20240903"
      engine_version: "7.2"
      method: "blacklist"
      result: null
    BitDefenderFalx:
      category: "type-unsupported"
      engine_name: "BitDefenderFalx"
      engine_update: "20240128"
      engine_version: "2.0.936"
      method: "blacklist"
      result: null
    BitDefenderTheta:
      category: "undetected"
      engine_name: "BitDefenderTheta"
      engine_update: "20240816"
      engine_version: "7.2.37796.0"
      method: "blacklist"
      result: null
    Bkav:
      category: "malicious"
      engine_name: "Bkav"
      engine_update: "20240903"
      engine_version: "2.0.0.1"
      method: "blacklist"
      result: "W64.AIDetectMalware"
    CAT-QuickHeal:
      category: "undetected"
      engine_name: "CAT-QuickHeal"
      engine_update: "20240902"
      engine_version: "22.00"
      method: "blacklist"
      result: null
    CMC:
      category: "undetected"
      engine_name: "CMC"
      engine_update: "20240903"
      engine_version: "2.4.2022.1"
      method: "blacklist"
      result: null
    ClamAV:
      category: "undetected"
      engine_name: "ClamAV"
      engine_update: "20240903"
      engine_version: "1.4.0.0"
      method: "blacklist"
      result: null
    CrowdStrike:
      category: "undetected"
      engine_name: "CrowdStrike"
      engine_update: "20231026"
      engine_version: "1.0"
      method: "blacklist"
      result: null
    Cybereason:
      category: "undetected"
      engine_name: "Cybereason"
      engine_update: "20240818"
      engine_version: "1.2.449"
      method: "blacklist"
      result: null
    Cylance:
      category: "undetected"
      engine_name: "Cylance"
      engine_update: "20240829"
      engine_version: "3.0.0.0"
      method: "blacklist"
      result: null
    Cynet:
      category: "undetected"
      engine_name: "Cynet"
      engine_update: "20240903"
      engine_version: "4.0.1.1"
      method: "blacklist"
      result: null
    DeepInstinct:
      category: "undetected"
      engine_name: "DeepInstinct"
      engine_update: "20240901"
      engine_version: "5.0.0.8"
      method: "blacklist"
      result: null
    DrWeb:
      category: "undetected"
      engine_name: "DrWeb"
      engine_update: "20240903"
      engine_version: "7.0.65.5230"
      method: "blacklist"
      result: null
    ESET-NOD32:
      category: "undetected"
      engine_name: "ESET-NOD32"
      engine_update: "20240903"
      engine_version: "29831"
      method: "blacklist"
      result: null
    Elastic:
      category: "undetected"
      engine_name: "Elastic"
      engine_update: "20240830"
      engine_version: "4.0.159"
      method: "blacklist"
      result: null
    Emsisoft:
      category: "undetected"
      engine_name: "Emsisoft"
      engine_update: "20240903"
      engine_version: "2024.1.0.53752"
      method: "blacklist"
      result: null
    F-Secure:
      category: "undetected"
      engine_name: "F-Secure"
      engine_update: "20240903"
      engine_version: "18.10.1547.307"
      method: "blacklist"
      result: null
    FireEye:
      category: "undetected"
      engine_name: "FireEye"
      engine_update: "20240903"
      engine_version: "35.47.0.0"
      method: "blacklist"
      result: null
    Fortinet:
      category: "undetected"
      engine_name: "Fortinet"
      engine_update: "20240903"
      engine_version: "None"
      method: "blacklist"
      result: null
    GData:
      category: "undetected"
      engine_name: "GData"
      engine_update: "20240903"
      engine_version: "A:25.38836B:27.37326"
      method: "blacklist"
      result: null
    Google:
      category: "malicious"
      engine_name: "Google"
      engine_update: "20240903"
      engine_version: "1725395433"
      method: "blacklist"
      result: "Detected"
    Gridinsoft:
      category: "undetected"
      engine_name: "Gridinsoft"
      engine_update: "20240903"
      engine_version: "1.0.186.174"
      method: "blacklist"
      result: null
    Ikarus:
      category: "malicious"
      engine_name: "Ikarus"
      engine_update: "20240903"
      engine_version: "6.3.12.0"
      method: "blacklist"
      result: "Trojan.Patched"
    Jiangmin:
      category: "undetected"
      engine_name: "Jiangmin"
      engine_update: "20240902"
      engine_version: "16.0.100"
      method: "blacklist"
      result: null
    K7AntiVirus:
      category: "undetected"
      engine_name: "K7AntiVirus"
      engine_update: "20240903"
      engine_version: "12.186.53144"
      method: "blacklist"
      result: null
    K7GW:
      category: "undetected"
      engine_name: "K7GW"
      engine_update: "20240903"
      engine_version: "12.186.53146"
      method: "blacklist"
      result: null
    Kaspersky:
      category: "undetected"
      engine_name: "Kaspersky"
      engine_update: "20240903"
      engine_version: "22.0.1.28"
      method: "blacklist"
      result: null
    Kingsoft:
      category: "undetected"
      engine_name: "Kingsoft"
      engine_update: "20240725"
      engine_version: "None"
      method: "blacklist"
      result: null
    Lionic:
      category: "undetected"
      engine_name: "Lionic"
      engine_update: "20240903"
      engine_version: "8.16"
      method: "blacklist"
      result: null
    MAX:
      category: "undetected"
      engine_name: "MAX"
      engine_update: "20240903"
      engine_version: "2023.1.4.1"
      method: "blacklist"
      result: null
    Malwarebytes:
      category: "undetected"
      engine_name: "Malwarebytes"
      engine_update: "20240903"
      engine_version: "4.5.5.54"
      method: "blacklist"
      result: null
    MaxSecure:
      category: "undetected"
      engine_name: "MaxSecure"
      engine_update: "20240903"
      engine_version: "1.0.0.1"
      method: "blacklist"
      result: null
    McAfee:
      category: "undetected"
      engine_name: "McAfee"
      engine_update: "20240903"
      engine_version: "6.0.6.653"
      method: "blacklist"
      result: null
    McAfeeD:
      category: "undetected"
      engine_name: "McAfeeD"
      engine_update: "20240903"
      engine_version: "1.2.0.7977"
      method: "blacklist"
      result: null
    MicroWorld-eScan:
      category: "undetected"
      engine_name: "MicroWorld-eScan"
      engine_update: "20240903"
      engine_version: "14.0.409.0"
      method: "blacklist"
      result: null
    Microsoft:
      category: "undetected"
      engine_name: "Microsoft"
      engine_update: "20240903"
      engine_version: "1.1.24070.3"
      method: "blacklist"
      result: null
    NANO-Antivirus:
      category: "undetected"
      engine_name: "NANO-Antivirus"
      engine_update: "20240903"
      engine_version: "1.0.146.25796"
      method: "blacklist"
      result: null
    Paloalto:
      category: "undetected"
      engine_name: "Paloalto"
      engine_update: "20240903"
      engine_version: "0.9.0.1003"
      method: "blacklist"
      result: null
    Panda:
      category: "undetected"
      engine_name: "Panda"
      engine_update: "20240903"
      engine_version: "4.6.4.2"
      method: "blacklist"
      result: null
    Rising:
      category: "undetected"
      engine_name: "Rising"
      engine_update: "20240903"
      engine_version: "25.0.0.27"
      method: "blacklist"
      result: null
    SUPERAntiSpyware:
      category: "undetected"
      engine_name: "SUPERAntiSpyware"
      engine_update: "20240902"
      engine_version: "5.6.0.1032"
      method: "blacklist"
      result: null
    Sangfor:
      category: "undetected"
      engine_name: "Sangfor"
      engine_update: "20240903"
      engine_version: "2.25.10.0"
      method: "blacklist"
      result: null
    SentinelOne:
      category: "undetected"
      engine_name: "SentinelOne"
      engine_update: "20240417"
      engine_version: "24.2.1.1"
      method: "blacklist"
      result: null
    Skyhigh:
      category: "undetected"
      engine_name: "Skyhigh"
      engine_update: "20240903"
      engine_version: "v2021.2.0+4045"
      method: "blacklist"
      result: null
    Sophos:
      category: "undetected"
      engine_name: "Sophos"
      engine_update: "20240903"
      engine_version: "2.5.5.0"
      method: "blacklist"
      result: null
    Symantec:
      category: "undetected"
      engine_name: "Symantec"
      engine_update: "20240903"
      engine_version: "1.22.0.0"
      method: "blacklist"
      result: null
    SymantecMobileInsight:
      category: "type-unsupported"
      engine_name: "SymantecMobileInsight"
      engine_update: "20240103"
      engine_version: "2.0"
      method: "blacklist"
      result: null
    TACHYON:
      category: "undetected"
      engine_name: "TACHYON"
      engine_update: "20240903"
      engine_version: "2024-09-03.02"
      method: "blacklist"
      result: null
    Tencent:
      category: "undetected"
      engine_name: "Tencent"
      engine_update: "20240903"
      engine_version: "1.0.0.1"
      method: "blacklist"
      result: null
    Trapmine:
      category: "malicious"
      engine_name: "Trapmine"
      engine_update: "20240826"
      engine_version: "4.0.16.213"
      method: "blacklist"
      result: "malicious.high.ml.score"
    TrendMicro:
      category: "undetected"
      engine_name: "TrendMicro"
      engine_update: "20240903"
      engine_version: "11.0.0.1006"
      method: "blacklist"
      result: null
    TrendMicro-HouseCall:
      category: "undetected"
      engine_name: "TrendMicro-HouseCall"
      engine_update: "20240903"
      engine_version: "10.0.0.1040"
      method: "blacklist"
      result: null
    Trustlook:
      category: "type-unsupported"
      engine_name: "Trustlook"
      engine_update: "20240903"
      engine_version: "1.0"
      method: "blacklist"
      result: null
    VBA32:
      category: "undetected"
      engine_name: "VBA32"
      engine_update: "20240903"
      engine_version: "5.0.0"
      method: "blacklist"
      result: null
    VIPRE:
      category: "undetected"
      engine_name: "VIPRE"
      engine_update: "20240903"
      engine_version: "6.0.0.35"
      method: "blacklist"
      result: null
    Varist:
      category: "undetected"
      engine_name: "Varist"
      engine_update: "20240903"
      engine_version: "6.5.1.2"
      method: "blacklist"
      result: null
    ViRobot:
      category: "undetected"
      engine_name: "ViRobot"
      engine_update: "20240903"
      engine_version: "2014.3.20.0"
      method: "blacklist"
      result: null
    VirIT:
      category: "undetected"
      engine_name: "VirIT"
      engine_update: "20240903"
      engine_version: "9.5.779"
      method: "blacklist"
      result: null
    Webroot:
      category: "undetected"
      engine_name: "Webroot"
      engine_update: "20240903"
      engine_version: "1.0.0.403"
      method: "blacklist"
      result: null
    Xcitium:
      category: "undetected"
      engine_name: "Xcitium"
      engine_update: "20240903"
      engine_version: "37015"
      method: "blacklist"
      result: null
    Yandex:
      category: "undetected"
      engine_name: "Yandex"
      engine_update: "20240903"
      engine_version: "5.5.2.24"
      method: "blacklist"
      result: null
    Zillya:
      category: "undetected"
      engine_name: "Zillya"
      engine_update: "20240903"
      engine_version: "2.0.0.5187"
      method: "blacklist"
      result: null
    ZoneAlarm:
      category: "undetected"
      engine_name: "ZoneAlarm"
      engine_update: "20240903"
      engine_version: "1.0"
      method: "blacklist"
      result: null
    Zoner:
      category: "undetected"
      engine_name: "Zoner"
      engine_update: "20240903"
      engine_version: "2.2.2.0"
      method: "blacklist"
      result: null
    alibabacloud:
      category: "undetected"
      engine_name: "alibabacloud"
      engine_update: "20240823"
      engine_version: "2.1.0"
      method: "blacklist"
      result: null
    huorong:
      category: "undetected"
      engine_name: "huorong"
      engine_update: "20240903"
      engine_version: "f611eab:f611eab:8cead27:8cead27"
      method: "blacklist"
      result: null
    tehtris:
      category: "undetected"
      engine_name: "tehtris"
      engine_update: "20240903"
      engine_version: "v0.1.4"
      method: "blacklist"
      result: null
  stats:
    confirmed-timeout: 0
    failure: 0
    harmless: 0
    malicious: 5
    suspicious: 0
    timeout: 0
    type-unsupported: 4
    undetected: 69
  status: "completed"

```
